name: 编译beikeyun-lean-18.06
on:
    schedule:
      - cron: 0 0 */7 * * 
    workflow_dispatch:

jobs:
    built:
        runs-on: ubuntu-20.04
        
        steps:
            - name: 安装编译依赖
              run: |
                id
                echo 工作目录:$PWD
                df -h
                docker rmi `docker images -q` > /dev/null 2>&1
                sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android > /dev/null 2>&1
                sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd*  > /dev/null 2>&1

                sudo apt update -y > /dev/null 2>&1
                sudo apt full-upgrade -y > /dev/null 2>&1
                sudo apt install -y ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential \
                bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
                git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
                libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
                mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils \
                rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev > /dev/null 2>&1
                
                sudo -E apt -y autoremove --purge > /dev/null 2>&1
                sudo -E apt clean > /dev/null 2>&1
                
                df -h
            - name: 下载仓库文件到工作目录
              uses: actions/checkout@v3
             
            - name: 克隆openwrt源码到工作目录
              run: |
                git clone https://github.com/coolsnowwolf/lede
            - name: 自定义修改
              run: |
                mv addCusPackage.sh lede/
                cd lede
                chmod +x addCusPackage.sh
                ./addCusPackage.sh
            - name: 更新feeds
              run: |
                cd lede
                ./scripts/feeds update -a > /dev/null 2>&1
                ./scripts/feeds install -a > /dev/null 2>&1
                ./scripts/feeds install -a
            - name: defconfig生成配置
              run: |
                cd lede
                rm -rf tmp
                mv -f ../armv8.config ./.config
                make defconfig
            - name: 开始编译
              run: |
                cd lede
                df -h 
                make -j8 download
                make -j8 download
                df -h
                make -j$(($(nproc) + 1))
            - name: 删除文件腾出打包空间
              run: |
                cd lede
                rm -rf build_dir
                rm -rf dl
                rm -rf tmp
                df -h 
            - name: Package Armvirt as OpenWrt
              uses: unifreq/openwrt_packit@master
              env:
                OPENWRT_ARMVIRT: lede/bin/targets/*/*/*rootfs.tar.gz
                PACKAGE_SOC: beikeyun
                KERNEL_VERSION_NAME: 5.4.202
            - name: 上传打包的固件-beikeyun
              uses: actions/upload-artifact@v3.1.1
              with:
                name: openwrt-flippy-beikeyun
                path: |
                    /opt/openwrt_packit/output/*beikeyun*

