name: Delete workflow runs
on:
    schedule:
      - cron: 0 0 * * * 
    workflow_dispatch:

jobs:
    built:
        runs-on: ubuntu-20.04
        steps:
            - name: Delete workflow runs
              uses: Mattraks/delete-workflow-runs@main
              with:
                token: ${{ github.token }}
                repository: ${{ github.repository }}
                retain_days: 2
                keep_minimum_runs: 0
