name: 编译openwrt-lean-18.06
on:
    schedule:
      - cron: 0 0 */7 * * 
    workflow_dispatch:

jobs:
    built:
        runs-on: ubuntu-20.04
        
        steps:
            - name: 安装编译依赖
              run: |
                id
                echo 工作目录:$PWD
                sudo apt update -y
                sudo apt full-upgrade -y
                sudo apt install -y ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential \
                bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
                git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
                libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
                mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils \
                rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

            - name: 下载仓库文件到工作目录
              uses: actions/checkout@v3
             
            - name: 克隆openwrt源码到工作目录
              run: |
                git clone https://github.com/coolsnowwolf/lede
            - name: 自定义修改
              run: |
                mv addCusPackage.sh lede/
                cd lede
                chmod +x addCusPackage.sh
                ./addCusPackage.sh
            - name: 更新feeds
              run: |
                cd lede
                ./scripts/feeds update -a > /dev/null 2>&1
                ./scripts/feeds install -a > /dev/null 2>&1
                ./scripts/feeds install -a
            - name: defconfig生成配置
              run: |
                cd lede
                rm -rf tmp
                mv -f ../x86.config ./.config
                make defconfig
            - name: 开始编译
              run: |
                cd lede
                
                make -j8 download
                make -j8 download
                make -j$(($(nproc) + 1)) 
            - name: 上传img固件
              uses: actions/upload-artifact@v3.1.1
              with:
                name: openwrt-combined
                path: |
                    lede/bin/targets/*/*/*combined*
            - name: 上传sysupgrade固件
              uses: actions/upload-artifact@v3.1.1
              with:
                name: openwrt-sysupgrade
                path: |
                    lede/bin/targets/*/*/*sysupgrade*
            
