name: 编译openwrt23.05
on:
    schedule:
      - cron: 0 0 */7 * * 
    workflow_dispatch:

jobs:
    built:
        runs-on: ubuntu-22.04
        
        steps:
            - name: 清理空间
              run: |
                id
                echo 工作目录:$PWD
                
                df -h

                docker rmi `docker images -q` 
                sudo rm -rf /usr/share/dotnet  /etc/php  
                sudo apt purge -y  dotnet*  php*

                df -h

            - name: 安装编译依赖
              run: |
                sudo apt update -y 
                sudo apt upgrade -y
                
                sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
                gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
                file wget
                
                #sudo apt install -y file clang ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential \
                #bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++ g++-multilib \
                #git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
                #libmpc-dev libmpfr-dev libncurses-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
                #mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-distutils python3-pip libpython3-dev qemu-utils \
                #rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev 
                
                sudo apt -y autoremove --purge 
                sudo apt clean 
                
                df -h
            - name: 下载仓库文件到工作目录
              uses: actions/checkout@v3
             
            - name: 克隆openwrt源码到工作目录
              run: |
                git clone -b openwrt-23.05 --depth=1 https://github.com/openwrt/openwrt.git
            - name: 自定义修改
              run: |
                mv addCusPackage-22.sh openwrt/
                cd openwrt
                chmod +x addCusPackage-22.sh
                ./addCusPackage-22.sh
            - name: 更新feeds
              run: |
                cd openwrt
                ./scripts/feeds update -a > /dev/null 2>&1
                ./scripts/feeds install -a > /dev/null 2>&1
                ./scripts/feeds install -a
            - name: fullcone补丁
              run: |
                mv fullcone-patch.sh openwrt/
                cd openwrt
                chmod +x fullcone-patch.sh
                ./fullcone-patch.sh
            - name: defconfig生成配置
              run: |
                cd openwrt
                rm -rf tmp
                mv -f ../x86.23.05.config ./.config
                make defconfig
            - name: 开始编译
              run: |
                cd openwrt
                
                make -j8 download
                make -j8 download
                make -j$(($(nproc) + 1)) 
            - name: 上传固件
              uses: actions/upload-artifact@v3.1.1
              with:
                name: openwrt-efi
                path: |
                    openwrt/bin/targets/*/*/*combined-efi.img*
                    
            - name: 上传固件
              uses: actions/upload-artifact@v3.1.1
              with:
                name: openwrt-legacy
                path: |
                    openwrt/bin/targets/*/*/*combined.img*
