name: 编译openwrt23.05
on:
    schedule:
      - cron: 0 0 */7 * * 
    workflow_dispatch:

jobs:
    built:
        runs-on: ubuntu-22.04
        
        steps:
            - name: 清理空间
              run: |
                id
                echo 工作目录:$PWD
                
                df -h

                docker rmi `docker images -q` >/dev/null
                sudo apt purge -y  dotnet* php* mysql* llvm*  >/dev/null
                
                sudo rm -rf /usr/share/dotnet  /etc/php  /etc/mysql /usr/local/lib/android >/dev/null
                
                df -h

            - name: 安装编译依赖
              run: |
                sudo apt update -y >/dev/null
                
                sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
                gettext git libncurses-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
                file wget >/dev/null
                
                sudo apt -y autoremove --purge >/dev/null
                sudo apt clean >/dev/null
                
                df -h
            - name: 下载仓库文件到工作目录
              uses: actions/checkout@v3
             
            - name: 克隆openwrt源码到工作目录
              run: |
                git clone -b openwrt-23.05 --depth=1 https://github.com/openwrt/openwrt.git

            - name: 更新feeds
              run: |
                cd openwrt
                ./scripts/feeds update -a > /dev/null 2>&1
                ./scripts/feeds install -a > /dev/null 2>&1
                ./scripts/feeds install -a
                
            - name: 自定义修改
              run: |
                mv addCusPackage-22.sh openwrt/
                cd openwrt
                chmod +x addCusPackage-22.sh
                ./addCusPackage-22.sh
                
            - name: 主页CPU信息补丁
              run: |
                mv patch-luci-status.sh openwrt/
                mv luci-status-patch.patch openwrt/
                cd openwrt
                chmod +x patch-luci-status.sh
                ./patch-luci-status.sh
                
            - name: fullcone补丁
              run: |
                mv fullcone-patch.sh openwrt/
                cd openwrt
                chmod +x fullcone-patch.sh
                ./fullcone-patch.sh
                
            - name: chinadefault设置
              run: |
                mv chinadefault.sh files.tar.gz openwrt/
                cd openwrt
                chmod +x chinadefault.sh
                ./chinadefault.sh

            - name: defconfig生成配置
              run: |
                cd openwrt
                rm -rf tmp
                mv -f ../x86.23.05.config ./.config
                make defconfig
            - name: 开始编译
              run: |
                cd openwrt
                
                make -j8 download
                make -j8 download
                make -j$(($(nproc) + 1)) 
                df -h
            - name: 上传固件
              uses: actions/upload-artifact@v3.1.1
              with:
                name: openwrt-efi
                path: |
                    openwrt/bin/targets/*/*/*combined-efi.img*
                    
            - name: 上传固件
              uses: actions/upload-artifact@v3.1.1
              with:
                name: openwrt-legacy
                path: |
                    openwrt/bin/targets/*/*/*combined.img*
