name: test
on:
    workflow_dispatch:

jobs:

    built:
        runs-on: ubuntu-22.04
        env:
         a: 1
         b: 2
        steps:

            - name: 下载仓库文件到工作目录
              uses: actions/checkout@v3
           
            - name: 变量
              id: output
              run: |
               chmod +x getLatestTag.sh
               echo "date=$(./getLatestTag.sh)" >> $GITHUB_OUTPUT
            - name: 上传固件
              uses: actions/upload-artifact@v3.1.1
              with:
                name: ${{steps.output.outputs.date}}ffff
                path: |
                    arm*
