name: test
on:
    workflow_dispatch:

jobs:

    built:
        runs-on: ubuntu-22.04
        env:
         a: 1
         b: 2
        steps:

            - name: 下载仓库文件到工作目录
              uses: actions/checkout@v3
           
            - name: 下载仓库文件到工作目录
              run: |
               a=3
               echo $a
               echo 'hi ${a}'
               echo "hi ${a}"
               echo "hi ${{a}}"
            - name: 上传固件
              uses: actions/upload-artifact@v3.1.1
              with:
                name: ${{env.a}}fff
                path: |
                    arm*
